### ISSUE TITLE
Disable-hwcrypto revert?

### ISSUE THREAD

**Issue by mateuseduardomedeiros** [vanhoefm/krackattacks-scripts#64]
as a return to standard? Wi-Fi is recognized but there are no available networks and etc ... Briefly, it stopped working

**Comment by roboluc** [comment]
You need to do the reverse of the disable-hwcrypto.sh script, so you need to delete all nohwcrypt=1 after every module in /etc/modprobe.d/nohwcrypt.conf

like this:

nano /etc/modprobe.d/nohwcrypt.conf

and the file needs to look like this:

options ath5k 
options ath9k
etc...

instead of this:
options ath5k nohwcrypt=1
options ath9k nohwcrypt=1
etc...

**Comment by vanhoefm** [comment]
It's also possible to simply remove the file `/etc/modprobe.d/nohwcrypt.conf`. I'll be adding a script for this as well.
