### ISSUE TITLE
Issue with Drivers

### ISSUE THREAD

**Issue by padmavathi101** [vanhoefm/krackattacks-scripts#68]
Configuration file: /root/krackattack/krackattack/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started
connect exception  hostapd_ctrl/wlan0 9877

Can you please suggest what might be this error?

**Comment by evilgash** [comment]
I have exactly the same issue. I am using an ALFA AWUS036H dongle and I think that causes the problem. However, I don't know why as it works fine with aircrack-ng tools.

Can anyone confirm that the AWUS036H adapter is not working for krackattack?

**Comment by evilgash** [comment]
I just checked hostapd and it says:

`nl80211: Failed to set interface 3 iftype 3: -95 (Operation not supported)`

I the checked which modes are supported by my ALFA AWUS036H and it turns out that AP is not supported (not in the output from iw list command):

```
iw list
...
Supported interface modes:
                  * IBSS
                  * managed
                  * monitor
....
```

Hence, I think my card is not supported to be used for the krackattack scripts.

**Comment by vanhoefm** [comment]
The card indeed isn't support, thanks for figuring it out!
