### ISSUE TITLE
krack-ft-test: Key-Handshake-Message 4 is not withheld

### ISSUE THREAD

**Issue by AnnabellBrocker** [vanhoefm/krackattacks-scripts#73]
Hey,

I am testing the krack-ft-test.py script in order to do a MitM attack within a Authenticator/Supplicant connection

I am using Kali Linux 2019.3 and have a PMF connection between the supplicant and the authenticator.
A correct connection is established, but when taking a look into the sniffed recordings (Wireshark) I do not see a double send of Key-Handshake-Message 3, which should appear because the foruth message should have been withheld. I also sniffed on a second wlan module in monitor mode and setted up the same radio-band and radio-channel for correct sniffing. There is also no double Message 3.

It seems that only a socket has been built which allows the bi-directional passage of messages, but that no MitM socket is built correctly because message 4 does not seem to be held back. Therefore, it is not possible to know the correct keys for injecting fake messages which the authenticator accepts.

**Comment by AnnabellBrocker** [comment]
I know that the script is only to detect if a device is vulnerable or not. But still I am missing the double presence of Message-3 in Wireshark. 

The socket which is opened (MitMSocket) should already do this, otherwise the name "MitMSocket" is misleading

**Comment by vanhoefm** [comment]
The MitmSocket mostly acts like a normal socket. The name comes from its original usage which has meanwhile been changed.

Note that the krack-ft-test checks if the FT handshake is vulnerable. Against the FT handshake, the adversary can simply replay message 3 of the FT handshake.

In the krack-test-client script for the 4-way handshake, no real attack is executed, meaning there is no need to block message 4. Since the script controls the AP, it can simply command the AP into sending a new message 3 to see how the client reacts to it.
